# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lin-H's notes
email: lh04667649@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website for Lin-H to take notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://note.lin-h.com" # the base hostname & protocol for your site
github_username:  Lin-H
timezone: Asia/Chongqing

excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown

sass:
  style: "compressed"

# gems:
#   - jekyll-assets
